---

- name: Copy haproxy configuration
  copy:
    dest: /etc/lb-haproxy.cfg
    content: "{{ haproxy_configuration }}"
    owner: root
    group: root
    mode: 0644
  register: haproxy_config

- name: lb container
  docker_container:
    name: "{{ haproxy_container_name }}"
    image: "haproxy:{{ haproxy_container_version }}"
    volumes:
      - "/etc/lb-haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    state: "started"
    restart_policy: "{{ haproxy_restart_policy }}"
    network_mode: "host"
    recreate: "{{ true if haproxy_config.changed else false }}"
    restart: "{{ true if haproxy_config.changed else false }}"
